### ISSUE TITLE
Exclude config ignored?

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/rubocop-bitcrowd#19]
I just set up a new Rails 5.2.2 project and added

* `rubocop@0.63.1`,
* `rubocop-bitcrowd@1.3.0` and
* `rubocop-rspec@1.31.0`.

I followed the setup instructions in the README. My RuboCop config looked like this:

```yaml
inherit_gem:
  rubocop-bitcrowd:
    - .rubocop.yml
    - .rubocop-rspec.yml
```

However, I noticed that issues inside of `node_modules` were reported.
I expected that directory to be ignored.

I found this in the RuboCop documentation: [Configuration: Merging arrays using inherit_mode](https://rubocop.readthedocs.io/en/latest/configuration/#merging-arrays-using-inherit_mode).

Appending the following to my `.rubocop.yml` fixed the issue for me:

```yaml
inherit_mode:
  merge:
    - Exclude
```

Does the README guide need an update? Did anyone else run into this and is there another solution?
